config/routes.rb
Article::Application.routes.draw do
  resources :clients

  devise_for :users

   resources :posts
   root :to => "posts#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :email, :login, :name
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :email, :mobile_no, :post_name, :user_name
validates :post_name, :user_name, :email, presence: true
validates :mobile_no, :length => { minimum: 10, maximum: 10 } 
validates :post_name, :length => { minimum:3, maximum:50 }
validates :user_name, :length => { minimum:2, maximum:15}

validates :mobile_no, presence: true, numericality: { only_integer: true }
has_one :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
# Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@client).deliver
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_filter :authenticate_user!
   
   def index   
  @posts = Post.paginate(:page => params[:page], :per_page => 16)
   end
   def new
  @post =Post.new
   end
   def create 
   @post = Post.new(params[:post])
   if @post.save
   redirect_to posts_path, :notice => "your post created sucessfully. "
   else 
   render "new"
   end
  end
  def update
  @post = Post.find(params[:id])
  if @post.update_attributes(params[:post])
  redirect_to posts_path, :notice => "your post updated sucessfully."
  else
  render "edit"
  end
  end
   def show
   @post = Post.find(params[:id])
   end
   def edit
   @post = Post.find(params[:id])
   end
   def destroy
    @post = Post.find(params[:id])
   @post.destroy
   redirect_to posts_path, :notice => "your post deleted sucssfully."
    end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Login</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.email %></td>
    <td><%= client.login %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Login:</b>
  <%= @client.login %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Article</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta charset="UTF-8">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>


<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="" align="center">
  <div class="field"><br>
    <%= f.label :post_name %><br>
    <%= f.text_field :post_name %>
  
 </div>
 <div class="field" ><br>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
<div class="field" ><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field"><br>
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div><br/><br/>
 
  <div class="action" >
    <%= f.submit "make", class: "btn btn-primary"%>
  </div><br>

</div></p>

<% end %>

app/views/posts/_slide.html.erb
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

        <!-- Carousel indicators -->

        <ol class="carousel-indicators">

            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

            <li data-target="#myCarousel" data-slide-to="1"></li>

            <li data-target="#myCarousel" data-slide-to="2"></li>

        </ol>   

        <!-- Carousel items -->

        <div class="carousel-inner">

            <div class="item active">
                            
            <img src="/assets/th.jpeg" alt="..." width="1350px" height="750px">
                <div class="carousel-caption">

                  <h3>First slide label</h3>

                  <p>Lorem ipsum dolor sit amet consectetur…</p>

                </div>

            </div>

            <div class="item">

                
                <img src="/assets/th1.jpeg" alt="..." width="1450px" height="750">
                <div class="carousel-caption">

                  <h3>Second slide label</h3>

                  <p>Aliquam sit amet gravida nibh, facilisis gravida…</p>

                </div>

            </div>

            <div class="item">

               
          <img src="/assets/th2.jpeg" alt="..." width="1450px" height="750">
                <div class="carousel-caption">

                  <h3>The universe is awsome & mysteries</h3>

                  <p>Praesent commodo cursus magna vel…</p>

                </div>

            </div>

        </div>

        <!-- Carousel nav -->

        <a class="carousel-control left" href="#myCarousel" data-slide="prev">

            <span class="glyphicon glyphicon-chevron-left"></span>

        </a>

        <a class="carousel-control right" href="#myCarousel" data-slide="next">

            <span class="glyphicon glyphicon-chevron-right"></span>

        </a>

    </div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form" %>
<%= link_to "Back", posts_path %>

app/views/posts/index.html.erb
<%= render "slide"%>
<br><br><br><h1 align="center">Listing Posts</h1>
<div class="table-responsive">
<table class="table" style="" align="center" border="1">
<div class="container-fluid">
  <tr>
    <th>Post Name</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Mobile No</th>
    <th colspan="5"></th>
  </tr>
 
<% @posts.each do |post| %>
  <tr>
    <td><%= post.post_name %></td>
    <td><%= post.user_name %></td>
    <td><%= post.email %></td>
    <td><%= post.mobile_no %></td>
    <td><%= link_to 'Show', post_path(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</div>
<% end %>
</table><br><br>
</div>
<p align="center"><%= link_to 'New Post', new_post_path %></p>


<p align="center"><%= will_paginate @posts%></p>

app/views/posts/new.html.erb
<%= render "slide"%>
<br><br><h1 align="center">Adding new post</h1>

<%= render "form"%>
<p align="center"><%= link_to "Back", posts_path %></p>

app/views/posts/show.html.erb
<%= render "slide"%>
<br><br><h1 align="center">Show post</h1>
<p align="center">
  <strong>Post name:</strong>
  <%= @post.post_name %>
</p>
 <p align="center">
  <strong>User name:</strong>
  <%= @post.user_name %>
</p>
<p align="center">
  <strong>Email:</strong>
  <%= @post.email %>
</p>
<p align="center">
  <strong>Mobile no:</strong>
  <%= @post.mobile_no %>
</p>
 
<p align="center"><%= link_to 'Back', posts_path %></p>